- name: starta  service
  hosts: all
  user: admin
  become: true
  tasks:
     - name: start apache
       service:
          name: httpd
          state: restarted

     - name: create a directory
       file: path=/tmp/kacst123 state=directory
